version: '3.8'
services:
  db:
    image: postgres:15.3-alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  cache:
    image:
      redis:7.2.5-alpine
      # restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning

  mailserver:
    image: maildev/maildev:2.1.0
    ports:
      - '1080:1080'
      - '1025:1025'
